extends SceneTree
const Recap=preload("res://defeat_recap.gd")
var checks:int=0
var failures:int=0
func _initialize():call_deferred("run")
func check(ok:bool,label:String)->void:
 checks+=1
 if ok:print("PASS ",label)
 else:failures+=1;push_error("FAIL "+label)
func dead(kind:String,built:float=1.0)->Dictionary:
 var subject:Dictionary={"kind":kind,"hp":0.0}
 if kind in ["hq","factory","barracks","vehicle_workshop","garden"]:subject["built"]=built
 return subject
func reject(recap:RefCounted,value:Variant,label:String)->void:
 var before:String=JSON.stringify(recap.snapshot())
 check(not Recap.validate(value,1,"921",100.0),label+" rejects before loading")
 check(not recap.restore(value,1,921,100.0) and JSON.stringify(recap.snapshot())==before,label+" preserves live state")
func run()->void:
 var recap=Recap.new()
 recap.reset(1,921)
 check(recap.recent_lines(100).is_empty(),"no losses produce no invented recap")
 check(not recap.record_loss({"kind":"factory","hp":1.0,"built":1.0},10),"living removed/dismantled factory cannot become a loss")
 check(not recap.record_loss(dead("guard"),10),"ordinary combat casualties do not flood strategic recap")
 check(not recap.record_loss(dead("worker"),NAN),"invalid timestamps are rejected")
 var factory=dead("factory")
 var node=Node3D.new();root.add_child(node);factory.node=node
 check(recap.record_loss(factory,12),"actual zero HP factory is recorded")
 node.free()
 check(not recap.record_loss(factory,13),"same loss cannot repeat after node free")
 check(recap.recent_lines(13)==["00:12  弾薬工房を喪失"],"freed-node fact keeps original timestamp and Japanese name")
 var worker1=dead("worker");var worker2=dead("worker");var worker3=dead("worker")
 recap.record_loss(worker1,20)
 recap.record_loss(dead("barracks"),22)
 recap.record_loss(worker2,24)
 recap.record_loss(worker3,26)
 var facts:Array=recap.recent_events(26)
 check(facts.size()==3 and facts.back().count==3 and facts.back().first_time==20 and facts.back().time==26,"workers merge within six-second window across an intervening facility loss")
 check(recap.recent_lines(26).back()=="00:20〜00:26  作業員 3人を喪失","cluster exposes actual count and time range")
 recap.record_loss(dead("worker"),26.1)
 check(recap.recent_events(27).back().count==1,"cluster window anchors at first loss and cannot stretch indefinitely")
 recap.record_loss(dead("vehicle_workshop",.5),30)
 check(recap.recent_lines(30).back()=="00:30  建設中の車両工房を喪失","unfinished facility is not described as completed production")
 check(recap.recent_lines(100).size()==3 and recap.recent_lines(100,2).size()==2,"recap displays at most three actual recent facts")
 check(recap.recent_lines(151).is_empty(),"facts older than two minutes do not appear as recent")
 var state:Dictionary=recap.snapshot()
 state.events.clear()
 check(not recap.snapshot().events.is_empty(),"snapshot does not expose mutable recorder storage")
 var encoded:String=JSON.stringify(recap.snapshot())
 var copy=Recap.new()
 check(copy.restore(JSON.parse_string(encoded),1,921,100) and copy.recent_lines(100)==recap.recent_lines(100),"JSON save/resume preserves facts and cluster boundaries")
 check(copy.snapshot()==recap.snapshot(),"JSON restore normalizes exact primitive record representation")
 copy.record_loss(dead("worker"),100)
 check(recap.recent_lines(100)!=copy.recent_lines(100),"restored records do not alias source recorder")
 var valid:Dictionary=recap.snapshot()
 var bad:Dictionary=valid.duplicate(true);bad.mission=2;reject(recap,bad,"different mission")
 bad=valid.duplicate(true);bad.run_seed="922";reject(recap,bad,"different run")
 bad=valid.duplicate(true);bad.events[0].time=101;reject(recap,bad,"future event")
 bad=valid.duplicate(true);bad.events[0].time=NAN;reject(recap,bad,"nonfinite event")
 bad=valid.duplicate(true);bad.events[0].kind="wall";reject(recap,bad,"unknown event kind")
 bad=valid.duplicate(true);bad.events[0].count=2;reject(recap,bad,"multiple facility loss in one event")
 bad=valid.duplicate(true);bad.events[0].node="invented";reject(recap,bad,"extra event field")
 bad=valid.duplicate(true);bad.events[0].unfinished="false";reject(recap,bad,"wrong boolean type")
 bad=valid.duplicate(true);bad.events.reverse();reject(recap,bad,"nonchronological records")
 bad=valid.duplicate(true);bad.events[2].first_time=10;reject(recap,bad,"overlong worker cluster")
 bad=valid.duplicate(true);bad.events[2].count=1.5;reject(recap,bad,"fractional worker count")
 bad=valid.duplicate(true)
 while bad.events.size()<=Recap.MAX_EVENTS:bad.events.append(valid.events.back().duplicate(true))
 reject(recap,bad,"unbounded event array")
 recap.reset(1,921)
 for index in 100:recap.record_loss(dead("factory"),float(index))
 check(recap.snapshot().events.size()==Recap.MAX_EVENTS and recap.snapshot().events[0].time==84,"100 losses retain only bounded latest sixteen records")
 recap.reset(1,921)
 var hq:Dictionary=dead("hq")
 var convoy:Dictionary=dead("convoy")
 var workers:Array=[dead("worker"),dead("worker"),convoy]
 var buildings:Array=[hq,dead("factory"),dead("barracks"),dead("vehicle_workshop")]
 recap.capture_losses(workers,buildings,100)
 var simultaneous:Dictionary=recap.snapshot()
 recap.capture_losses(workers,buildings,100)
 check(recap.snapshot()==simultaneous,"terminal capture and repeated cleanup remain idempotent")
 check(recap.recent_events(100).size()==3 and recap.recent_events(100).any(func(event):return event.kind in ["hq","convoy"]),"terminal loss remains visible when many losses share a tick")
 check(recap.snapshot().events[0].count==2,"terminal early return retains pending worker casualties")
 recap.reset(2,922)
 check(recap.snapshot().events.is_empty() and recap.recent_lines(0).is_empty(),"retry/new mission resets all old facts")
 print("DEFEAT_RECAP_SUMMARY checks=%d failures=%d"%[checks,failures])
 quit(0 if failures==0 else 1)
